### ISSUE TITLE
Trying to create Azure resources but azure CLI missing from runner

### ISSUE THREAD

**Issue by masterphenix** [weaveworks/tf-controller#221]
Hello,
I have installed the terraform controller on our kubernetes cluster using the Helm Chart, and successfully configured a gitRepository pointing to a terraform workspace. 
Howerver, this workspace uses the azure_rm provider to build Azure resources, which requires Azure CLI to be installed in the runner :
```
{"level":"error","ts":"2022-05-03T09:49:31.375Z","logger":"controller.terraform","msg":"Reconciliation failed after 16.905672785s, next try in 1m0s","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"terraform-playground-postgresql","namespace":"flux","revision":"master/8b307366408515292837f38cd8a0d97498c8f89f","error":"error running Plan: rpc error: code = Unknown desc = exit status 1\n\nError: building AzureRM Client: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: \"az\": executable file not found in $PATH.\n\n  with provider[\"registry.terraform.io/hashicorp/azurerm\"],\n  on common.tf line 3, in provider \"azurerm\":\n   3: provider \"azurerm\" {\n\n"}
```
Is there a way to customize the runner to add the missing tools ?

**Comment by tomhuang12** [comment]
@masterphenix Yes! The runner dockerfile is [here](https://github.com/weaveworks/tf-controller/blob/main/runner.Dockerfile). You can simply add the dependencies you need, build and push to a registry. To replace the runner image, if you are using the chart, simply override `runner.image.repository` and `runner.image.tag` in values to your image to use it.

**Comment by masterphenix** [comment]
@tomhuang12 thank you for your quick reply ; I did find and tweak the runner.Dockerfile afterwards.
Now, since I changed the runner image, I have 2 new issues :

a) I need to authenticate to Azure by using 'az login' in the runner before doing anything else :
```
{"level":"error","ts":"2022-05-03T14:34:12.121Z","logger":"controller.terraform","msg":"Reconciliation failed after 14.539713192s, next try in 1m0s","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"terraform-playground-postgresql","namespace":"flux","revision":"master/8b307366408515292837f38cd8a0d97498c8f89f","error":"error running Plan: rpc error: code = Unknown desc = exit status 1\n\nError: building AzureRM Client: obtain subscription(xxxx-xxxxx-xxxx) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.\n\n  with provider[\"registry.terraform.io/hashicorp/azurerm\"],\n  on common.tf line 3, in provider \"azurerm\":\n   3: provider \"azurerm\" {\n\n"}
```
To do that, I would like to use Azure Managed Identity (by using AAD Pod Identity), which requires to set a label on the runnner Pod : this doesn't seem to be an option yet, maybe I should create a separate issue for this ?

b) Right after the previous error, the controller exits with a panic error :
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x148e069]

goroutine 398 [running]:
github.com/fluxcd/pkg/runtime/events.(*Recorder).AnnotatedEventf(0x0, {0x1bef760, 0xc0001c7200}, 0xc003d61bf0, {0x1995f5e, 0x7}, {0x19a1f9c, 0x2}, {0xc0000125a0, 0x1c2}, ...)
        /go/pkg/mod/github.com/fluxcd/pkg/runtime@v0.13.2/events/recorder.go:124 +0x69
github.com/weaveworks/tf-controller/controllers.(*TerraformReconciler).fireEvent(_, {_, _}, {{{0x163a1d9, 0x9}, {0xc00047ea40, 0x20}}, {{0xc0005ea4a0, 0x1f}, {0x0, ...}, ...}, ...}, ...)
        /workspace/controllers/terraform_controller.go:1436 +0x258
github.com/weaveworks/tf-controller/controllers.(*TerraformReconciler).Reconcile(0xc0003d52c0, {0x1c06628, 0xc000801500}, {{{0xc000554728, 0x4}, {0xc0005ea4a0, 0x1f}}})
        /workspace/controllers/terraform_controller.go:281 +0x1875
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000148000, {0x1c06628, 0xc000801470}, {{{0xc000554728, 0x18ca8a0}, {0xc0005ea4a0, 0x413c54}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000148000, {0x1c06580, 0xc0009c8640}, {0x17ea780, 0xc00009f060})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000148000, {0x1c06580, 0xc0009c8640})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by tomhuang12** [comment]
Thanks for the update. Yeah currently there isn't an easy way

**Comment by tomhuang12** [comment]
^ fat fingerred it 😅

**Comment by tomhuang12** [comment]
@masterphenix the next release should include runner pod label customizing feature. Feel free to install it from main branch if you would like to use it now :).

**Comment by tomhuang12** [comment]
@danielsollondon this is released as part of v0.9.5 release.

**Comment by tomhuang12** [comment]
Hi @masterphenix, I am trying to get this to work in my AKS using AAD without success and wondering how you got it to work. The backend config looks like:
```
terraform {
  backend "azurerm" {
    storage_account_name = "abcd1234"
    container_name       = "tfstate"
    key                  = "prod.terraform.tfstate"
    use_azuread_auth     = true
    subscription_id      = "00000000-0000-0000-0000-000000000000"
    tenant_id            = "00000000-0000-0000-0000-000000000000"
  }
}
```

The error I am getting is:
```
error running Init: rpc error: code = Internal desc = exit status 1\n\nError: Error building ARM Config: obtain subscription(REDACTED) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
```

**Comment by masterphenix** [comment]
Hello @tomhuang12 , I didn't get it to work, in fact, I hadn't got the chance to get back on this since az CLI was included in the project. To get AAD Pod Identity to work, you need to be able to set the binding label on the runner pods, which was not possible when I got stuck in may, Is it possible now ? Did you do that ?

**Comment by tomhuang12** [comment]
@masterphenix Yeah, it is documented [here](https://weaveworks.github.io/tf-controller/use_cases/#customize-runner-pod-metadata). I am able to get it to work with a service principal but not AAD.

**Comment by masterphenix** [comment]
Hello @tomhuang12 , I dig get to reproduce your issue, and I managed to fix it with the use_msi field of the terraform provider:
```
provider "azurerm" {
  subscription_id = "xxxxxxxxx"
  tenant_id       = "xxxxxxxx"
  use_msi = true
  features {}
}
```
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#use_msi

**Comment by tomhuang12** [comment]
@masterphenix thank you!
